### ISSUE TITLE
Move AutoSaveStatusProvider to beam

### ISSUE THREAD

**Issue by stephenh** [homebound-team/form-state#80]
Originally we thought that form-state's autoSave methods would need to trigger auto-save statuses.

However, we've since added the `apolloHooks.ts` instrumentation in internal-frontend that hooks all mutations up to the auto-save status. Which actually works better b/c some of the schedule page's mutations weren't going through form-state.

Given this new slice point, we should be able to move AutoSaveStatusProvider to beam and not have form-state itself need to know/trigger it anymore.

**Comment by TylerR909** [comment]
So how do non `internal-frontend` projects get access to "A save is going on right now"?

**Comment by stephenh** [comment]
This was done a few months ago
